/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: EasyPusher.i */

#define SWIGMODULE EasyPusher
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}


   #include "EasyTypes.h"
   #include "EasyPusherAPI.h"
   extern Easy_I32 GO_EasyPusher_Activate(char *license);
   extern Easy_Pusher_Handle GO_EasyPusher_Create();
   extern Easy_U32 GO_EasyPusher_StartStream(Easy_Pusher_Handle handle, char* serverAddr, Easy_U16 port, char* streamName, char *username, char *password, EASY_MEDIA_INFO_T*  pstruStreamInfo, Easy_U32 bufferKSize, Easy_Bool createlogfile );
   extern Easy_U32 GO_EasyPusher_StopStream(Easy_Pusher_Handle handle);
   extern Easy_U32 GO_EasyPusher_PushFrame(Easy_Pusher_Handle handle, EASY_AV_Frame* frame );

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_EasyPusher_993691126ef1af58(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


Easy_I32 *_wrap_GO_EasyPusher_Activate_EasyPusher_993691126ef1af58(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  Easy_I32 result;
  Easy_I32 *_swig_go_result;
  
  arg1 = (char *)_swig_go_0.p; 
  
  result = GO_EasyPusher_Activate(arg1);
  {
    Easy_I32 * resultptr = (Easy_I32 *)malloc(sizeof(Easy_I32));
    memmove(resultptr, &result, sizeof(Easy_I32));
    *(Easy_I32 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Easy_Pusher_Handle *_wrap_GO_EasyPusher_Create_EasyPusher_993691126ef1af58() {
  Easy_Pusher_Handle result;
  Easy_Pusher_Handle *_swig_go_result;
  
  
  result = GO_EasyPusher_Create();
  {
    Easy_Pusher_Handle * resultptr = (Easy_Pusher_Handle *)malloc(sizeof(Easy_Pusher_Handle));
    memmove(resultptr, &result, sizeof(Easy_Pusher_Handle));
    *(Easy_Pusher_Handle **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Easy_U32 *_wrap_GO_EasyPusher_StartStream_EasyPusher_993691126ef1af58(Easy_Pusher_Handle *_swig_go_0, _gostring_ _swig_go_1, Easy_U16 *_swig_go_2, _gostring_ _swig_go_3, _gostring_ _swig_go_4, _gostring_ _swig_go_5, EASY_MEDIA_INFO_T *_swig_go_6, Easy_U32 *_swig_go_7, Easy_Bool *_swig_go_8) {
  Easy_Pusher_Handle arg1 ;
  char *arg2 = (char *) 0 ;
  Easy_U16 arg3 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  char *arg6 = (char *) 0 ;
  EASY_MEDIA_INFO_T *arg7 = (EASY_MEDIA_INFO_T *) 0 ;
  Easy_U32 arg8 ;
  Easy_Bool arg9 ;
  Easy_Pusher_Handle *argp1 ;
  Easy_U16 *argp3 ;
  Easy_U32 *argp8 ;
  Easy_Bool *argp9 ;
  Easy_U32 result;
  Easy_U32 *_swig_go_result;
  
  
  argp1 = (Easy_Pusher_Handle *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_Pusher_Handle");
  }
  arg1 = (Easy_Pusher_Handle)*argp1;
  
  arg2 = (char *)_swig_go_1.p; 
  
  argp3 = (Easy_U16 *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_U16");
  }
  arg3 = (Easy_U16)*argp3;
  
  arg4 = (char *)_swig_go_3.p; 
  arg5 = (char *)_swig_go_4.p; 
  arg6 = (char *)_swig_go_5.p; 
  arg7 = *(EASY_MEDIA_INFO_T **)&_swig_go_6; 
  
  argp8 = (Easy_U32 *)_swig_go_7;
  if (argp8 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_U32");
  }
  arg8 = (Easy_U32)*argp8;
  
  
  argp9 = (Easy_Bool *)_swig_go_8;
  if (argp9 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_Bool");
  }
  arg9 = (Easy_Bool)*argp9;
  
  
  result = GO_EasyPusher_StartStream(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  {
    Easy_U32 * resultptr = (Easy_U32 *)malloc(sizeof(Easy_U32));
    memmove(resultptr, &result, sizeof(Easy_U32));
    *(Easy_U32 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Easy_U32 *_wrap_GO_EasyPusher_StopStream_EasyPusher_993691126ef1af58(Easy_Pusher_Handle *_swig_go_0) {
  Easy_Pusher_Handle arg1 ;
  Easy_Pusher_Handle *argp1 ;
  Easy_U32 result;
  Easy_U32 *_swig_go_result;
  
  
  argp1 = (Easy_Pusher_Handle *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_Pusher_Handle");
  }
  arg1 = (Easy_Pusher_Handle)*argp1;
  
  
  result = GO_EasyPusher_StopStream(arg1);
  {
    Easy_U32 * resultptr = (Easy_U32 *)malloc(sizeof(Easy_U32));
    memmove(resultptr, &result, sizeof(Easy_U32));
    *(Easy_U32 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Easy_U32 *_wrap_GO_EasyPusher_PushFrame_EasyPusher_993691126ef1af58(Easy_Pusher_Handle *_swig_go_0, EASY_AV_Frame *_swig_go_1) {
  Easy_Pusher_Handle arg1 ;
  EASY_AV_Frame *arg2 = (EASY_AV_Frame *) 0 ;
  Easy_Pusher_Handle *argp1 ;
  Easy_U32 result;
  Easy_U32 *_swig_go_result;
  
  
  argp1 = (Easy_Pusher_Handle *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null Easy_Pusher_Handle");
  }
  arg1 = (Easy_Pusher_Handle)*argp1;
  
  arg2 = *(EASY_AV_Frame **)&_swig_go_1; 
  
  result = GO_EasyPusher_PushFrame(arg1,arg2);
  {
    Easy_U32 * resultptr = (Easy_U32 *)malloc(sizeof(Easy_U32));
    memmove(resultptr, &result, sizeof(Easy_U32));
    *(Easy_U32 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

